# NOTE: update this with your service name
service: tablesfortwo-notifier

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  alerts:
    topics:
      alarm: ${file(./env.yml):prod.AWS_SNS_ALARMS_ARN}
    alarms:
      - functionErrors

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  memorySize: 128
  timeout: 30
  versionFunctions: true
  environment: ${file(./env.yml):prod}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  main:
    handler: handler.handle
    events:
      - schedule:
          name: tablesfortwo-cron
          rate: cron(0 14 ? * WED *) # 2pm Wed
    alarms:
      - functionErrors
